### ISSUE TITLE
Food Stack reduction works, but block size reduction does not, since the weight config update

### ISSUE THREAD

**Issue by sharlin073** [Insane96/IguanaTweaksReborn#132] opened 2021-03-13 06:38 UTC
Follow the following guideline. Not following this will result in ignored and closed issue.

// Usually only latest versions are supported

**Minecraft Version**: 1.16.5 

// Please make sure you're using the latest version before sending a report

Mod Version: IguanaTweaksReborn-2.4.4-mc1.16.x

**Forge Version**: Forge 36.0.42

**What Happens**: Food Stack reduction works, but block size reduction does not, since the weight config update.

//Please send logs even if you don't have any crash, and use Gist or Pastebin

**Logs / Crash reports**: 
https://pastebin.com/VjQ3ZMYf

//If different from default
**Config**: default (removed the config and re-ran with this mod alone)

**List of mods installed / modpack**:
This mod alone.

**Comment by sharlin073** [comment] 2021-03-13 06:45
It seems like the log file does not show what I did. I joined a flat world in creative mod, picked some blocks to check the max stack size, and logged out.

**Comment by Insane96** [comment] 2021-03-13 08:04
Can't reproduce with Forge 36.0.55

**Comment by sharlin073** [comment] 2021-03-13 10:54
Thanks a lot! I just updated the forge.

Sadly the new version of Forge generates so many WARN in the log file, so I need to check if others also work correctly though. :P

**Comment by sharlin073** [comment] 2021-03-13 20:49
Here's log from the latest Forge version

[05:46:45] [main/INFO]: ModLauncher running: args [--username, bluebird9281, --version, forge-36.0.55, --gameDir, C:\Users\ysc\Twitch\Minecraft\Instances\Iguana Test, --assetsDir, C:\Users\ysc\Twitch\Minecraft\Install\assets, --assetIndex, 1.16, --uuid, 63800a934e6248de95094e36f2efc2ce, --accessToken, ????????, --userType, mojang, --versionType, release, --width, 1024, --height, 768, --launchTarget, fmlclient, --fml.forgeVersion, 36.0.55, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20210115.111550]
[05:46:45] [main/INFO]: ModLauncher 8.0.9+86+master.3cf110c starting: java version 1.8.0_51 by Oracle Corporation
[05:46:45] [main/WARN]: LEGACY JDK DETECTED, SECURED JAR HANDLING DISABLED
[05:46:46] [main/INFO]: Added Lets Encrypt root certificates as additional trust
[05:46:46] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/C:/Users/ysc/Twitch/Minecraft/Install/libraries/org/spongepowered/mixin/0.8.2/mixin-0.8.2.jar Service=ModLauncher Env=CLIENT
[05:46:48] [main/INFO]: Launching target 'fmlclient' with arguments [--version, forge-36.0.55, --gameDir, C:\Users\ysc\Twitch\Minecraft\Instances\Iguana Test, --assetsDir, C:\Users\ysc\Twitch\Minecraft\Install\assets, --uuid, 63800a934e6248de95094e36f2efc2ce, --username, bluebird9281, --assetIndex, 1.16, --accessToken, ????????, --userType, mojang, --versionType, release, --width, 1024, --height, 768]
[05:46:53] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[05:46:54] [Render thread/INFO]: Setting user: bluebird9281
[05:46:54] [Render thread/INFO]: Backend library: LWJGL version 3.2.2 build 10
[05:46:55] [modloading-worker-3/INFO]: Forge mod loading, version 36.0.55, for MC 1.16.5 with MCP 20210115.111550
[05:46:55] [modloading-worker-3/INFO]: MinecraftForge v36.0.55 Initialized
[05:46:56] [Render thread/INFO]: Narrator library for x64 successfully loaded
[05:46:56] [Render thread/INFO]: Reloading ResourceManager: Default, Mod Resources
[05:46:57] [modloading-worker-2/WARN]: Invalid material "ANVIL,6" for Material Weight
[05:46:57] [modloading-worker-2/WARN]: Invalid material "BAMBOO,2" for Material Weight
[05:46:57] [modloading-worker-2/WARN]: Invalid material "BAMBOO_SAPLING,2" for Material Weight
[05:46:57] [modloading-worker-2/WARN]: Invalid material "BARRIER,1" for Material Weight
[05:46:57] [modloading-worker-2/WARN]: Invalid material "CACTUS,2" for Material Weight
[05:46:57] [modloading-worker-2/WARN]: Invalid material "CAKE,2" for Material Weight
[05:46:57] [modloading-worker-2/WARN]: Invalid material "CARPET,2" for Material Weight
[05:46:57] [modloading-worker-2/WARN]: Invalid material "CLAY,3" for Material Weight
[05:46:57] [modloading-worker-2/WARN]: Invalid material "CORAL,2" for Material Weight
[05:46:57] [modloading-worker-2/WARN]: Invalid material "DRAGON_EGG,1" for Material Weight
[05:46:57] [modloading-worker-2/WARN]: Invalid material "EARTH,2" for Material Weight
[05:46:57] [modloading-worker-2/WARN]: Invalid material "GLASS,2" for Material Weight
[05:46:57] [modloading-worker-2/WARN]: Invalid material "GOURD,2" for Material Weight
[05:46:57] [modloading-worker-2/WARN]: Invalid material "ICE,3" for Material Weight
[05:46:57] [modloading-worker-2/WARN]: Invalid material "IRON,6" for Material Weight
[05:46:57] [modloading-worker-2/WARN]: Invalid material "LEAVES,2" for Material Weight
[05:46:57] [modloading-worker-2/WARN]: Invalid material "MISCELLANEOUS,2" for Material Weight
[05:46:57] [modloading-worker-2/WARN]: Invalid material "NETHER_PLANTS,2" for Material Weight
[05:46:57] [modloading-worker-2/WARN]: Invalid material "NETHER_WOOD,3" for Material Weight
[05:46:57] [modloading-worker-2/WARN]: Invalid material "OCEAN_PLANT,2" for Material Weight
[05:46:57] [modloading-worker-2/WARN]: Invalid material "ORGANIC,3" for Material Weight
[05:46:57] [modloading-worker-2/WARN]: Invalid material "PACKED_ICE,4" for Material Weight
[05:46:57] [modloading-worker-2/WARN]: Invalid material "PISTON,2" for Material Weight
[05:46:57] [modloading-worker-2/WARN]: Invalid material "PLANTS,2" for Material Weight
[05:46:57] [modloading-worker-2/WARN]: Invalid material "REDSTONE_LIGHT,2" for Material Weight
[05:46:57] [modloading-worker-2/WARN]: Invalid material "ROCK,4" for Material Weight
[05:46:57] [modloading-worker-2/WARN]: Invalid material "SAND,2" for Material Weight
[05:46:57] [modloading-worker-2/WARN]: Invalid material "SEA_GRASS,2" for Material Weight
[05:46:57] [modloading-worker-2/WARN]: Invalid material "SHULKER,1" for Material Weight
[05:46:57] [modloading-worker-2/WARN]: Invalid material "SNOW,2" for Material Weight
[05:46:57] [modloading-worker-2/WARN]: Invalid material "SNOW_BLOCK,3" for Material Weight
[05:46:57] [modloading-worker-2/WARN]: Invalid material "SPONGE,2" for Material Weight
[05:46:57] [modloading-worker-2/WARN]: Invalid material "TALL_PLANTS,2" for Material Weight
[05:46:57] [modloading-worker-2/WARN]: Invalid material "TNT,2" for Material Weight
[05:46:57] [modloading-worker-2/WARN]: Invalid material "WEB,2" for Material Weight
[05:46:57] [modloading-worker-2/WARN]: Invalid material "WOOD,3" for Material Weight
[05:46:57] [modloading-worker-2/WARN]: Invalid material "WOOL,4" for Material Weight
[05:46:57] [modloading-worker-2/WARN]: vulcanite:vulcanite_hoe item for Hoe Till Chance seems to not exist
[05:46:57] [Thread-1/WARN]: Invalid material "ANVIL,6" for Material Weight
[05:46:57] [Thread-1/WARN]: Invalid material "BAMBOO,2" for Material Weight
[05:46:57] [Thread-1/WARN]: Invalid material "BAMBOO_SAPLING,2" for Material Weight
[05:46:57] [Thread-1/WARN]: Invalid material "BARRIER,1" for Material Weight
[05:46:57] [Thread-1/WARN]: Invalid material "CACTUS,2" for Material Weight
[05:46:57] [Thread-1/WARN]: Invalid material "CAKE,2" for Material Weight
[05:46:57] [Thread-1/WARN]: Invalid material "CARPET,2" for Material Weight
[05:46:57] [Thread-1/WARN]: Invalid material "CLAY,3" for Material Weight
[05:46:57] [Thread-1/WARN]: Invalid material "CORAL,2" for Material Weight
[05:46:57] [Thread-1/WARN]: Invalid material "DRAGON_EGG,1" for Material Weight
[05:46:57] [Thread-1/WARN]: Invalid material "EARTH,2" for Material Weight
[05:46:57] [Thread-1/WARN]: Invalid material "GLASS,2" for Material Weight
[05:46:57] [Thread-1/WARN]: Invalid material "GOURD,2" for Material Weight
[05:46:57] [Thread-1/WARN]: Invalid material "ICE,3" for Material Weight
[05:46:57] [Thread-1/WARN]: Invalid material "IRON,6" for Material Weight
[05:46:57] [Thread-1/WARN]: Invalid material "LEAVES,2" for Material Weight
[05:46:57] [Thread-1/WARN]: Invalid material "MISCELLANEOUS,2" for Material Weight
[05:46:57] [Thread-1/WARN]: Invalid material "NETHER_PLANTS,2" for Material Weight
[05:46:57] [Thread-1/WARN]: Invalid material "NETHER_WOOD,3" for Material Weight
[05:46:57] [Thread-1/WARN]: Invalid material "OCEAN_PLANT,2" for Material Weight
[05:46:57] [Thread-1/WARN]: Invalid material "ORGANIC,3" for Material Weight
[05:46:57] [Thread-1/WARN]: Invalid material "PACKED_ICE,4" for Material Weight
[05:46:57] [Thread-1/WARN]: Invalid material "PISTON,2" for Material Weight
[05:46:57] [Thread-1/WARN]: Invalid material "PLANTS,2" for Material Weight
[05:46:57] [Thread-1/WARN]: Invalid material "REDSTONE_LIGHT,2" for Material Weight
[05:46:57] [Thread-1/WARN]: Invalid material "ROCK,4" for Material Weight
[05:46:57] [Thread-1/WARN]: Invalid material "SAND,2" for Material Weight
[05:46:57] [Thread-1/WARN]: Invalid material "SEA_GRASS,2" for Material Weight
[05:46:57] [Thread-1/WARN]: Invalid material "SHULKER,1" for Material Weight
[05:46:57] [Thread-1/WARN]: Invalid material "SNOW,2" for Material Weight
[05:46:57] [Thread-1/WARN]: Invalid material "SNOW_BLOCK,3" for Material Weight
[05:46:57] [Thread-1/WARN]: Invalid material "SPONGE,2" for Material Weight
[05:46:57] [Thread-1/WARN]: Invalid material "TALL_PLANTS,2" for Material Weight
[05:46:57] [Thread-1/WARN]: Invalid material "TNT,2" for Material Weight
[05:46:57] [Thread-1/WARN]: Invalid material "WEB,2" for Material Weight
[05:46:57] [Thread-1/WARN]: Invalid material "WOOD,3" for Material Weight
[05:46:57] [Thread-1/WARN]: Invalid material "WOOL,4" for Material Weight
[05:46:57] [Thread-1/WARN]: vulcanite:vulcanite_hoe item for Hoe Till Chance seems to not exist
[05:46:57] [Forge Version Check/INFO]: [forge] Starting version check at https://files.minecraftforge.net/maven/net/minecraftforge/forge/promotions_slim.json
[05:46:58] [Forge Version Check/INFO]: [forge] Found status: BETA_OUTDATED Current: 36.0.55 Target: 36.0.58
[05:47:01] [Render thread/INFO]: OpenAL initialized.
[05:47:01] [Render thread/INFO]: Sound engine started
[05:47:01] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/blocks.png-atlas
[05:47:02] [Render thread/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[05:47:02] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[05:47:02] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[05:47:02] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[05:47:02] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[05:47:02] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[05:47:02] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[05:47:02] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[05:47:02] [Render thread/INFO]: Created: 128x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[05:47:45] [Render thread/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
[05:47:45] [Render thread/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[05:47:45] [Render thread/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[05:47:45] [Render thread/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[05:47:45] [Render thread/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[05:47:45] [Render thread/INFO]: Reloading ResourceManager: Default, IguanaTweaksReborn-2.4.4-mc1.16.x.jar, forge-1.16.5-36.0.55-universal.jar
[05:47:46] [Render thread/INFO]: Loaded 7 recipes
[05:47:46] [Render thread/INFO]: Loaded 927 advancements
[05:47:46] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[05:47:46] [Server thread/INFO]: Starting integrated minecraft server version 1.16.5
[05:47:46] [Server thread/INFO]: Generating keypair
[05:47:46] [Server thread/WARN]: Configuration file C:\Users\ysc\Twitch\Minecraft\Instances\Iguana Test\saves\New World\serverconfig\forge-server.toml is not correct. Correcting
[05:47:46] [Server thread/WARN]: Incorrect key server was corrected from null to its default, SimpleCommentedConfig:{}. 
[05:47:46] [Server thread/WARN]: Incorrect key server.removeErroringEntities was corrected from null to its default, false. 
[05:47:46] [Server thread/WARN]: Incorrect key server.removeErroringTileEntities was corrected from null to its default, false. 
[05:47:46] [Server thread/WARN]: Incorrect key server.fullBoundingBoxLadders was corrected from null to its default, false. 
[05:47:46] [Server thread/WARN]: Incorrect key server.zombieBaseSummonChance was corrected from null to its default, 0.1. 
[05:47:46] [Server thread/WARN]: Incorrect key server.zombieBabyChance was corrected from null to its default, 0.05. 
[05:47:46] [Server thread/WARN]: Incorrect key server.logCascadingWorldGeneration was corrected from null to its default, true. 
[05:47:46] [Server thread/WARN]: Incorrect key server.fixVanillaCascading was corrected from null to its default, false. 
[05:47:46] [Server thread/WARN]: Incorrect key server.dimensionUnloadQueueDelay was corrected from null to its default, 0. 
[05:47:46] [Server thread/WARN]: Incorrect key server.treatEmptyTagsAsAir was corrected from null to its default, false. 
[05:47:46] [Server thread/WARN]: Incorrect key server.fixAdvancementLoading was corrected from null to its default, true.

**Comment by Insane96** [comment] 2021-03-13 21:23
I think I understood why I don't have the problem. Tomorrow I'll test it

**Comment by sharlin073** [comment] 2021-03-14 14:30
Thanks a lot! :)

**Comment by Insane96** [comment] 2021-03-15 08:15
I have to revert the config for weights, sadly it's not doable

**Comment by sharlin073** [comment] 2021-03-15 08:58
oh... okay.

**Comment by sharlin073** [comment] 2021-03-18 21:36
Hi! I'm sorry for being impatient, but will there be another release soon with config revert? :)

**Comment by Insane96** [comment] 2021-04-03 10:46
Fixed in 2.5.0

**Closed by Insane96** 2021-04-03 10:46 UTC
Labels: bug

**Comment by sharlin073** [comment] 2021-04-03 11:30
Wow thank you so much :P

**Comment by Insane96** [comment] 2021-04-03 11:43
Sorry for the delay but had so many problems with my laptop

**Comment by sharlin073** [comment] 2021-04-03 11:45
Sorry to hear that, and glad it got fixed now.

No worries. I'm really happy with the experience this mod provides :)

**Comment by Insane96** [comment] 2021-04-03 11:48
> Sorry to hear that, and glad the laptap got fixed now.

Well no. 
Long story short, my old laptop is dying so bought a new one but the new one doesn't work so I'm back to my old one that only god knows how it still works.

Also 2.5.1* (changed some more things) will be released as soon as CurseForge approves my Library mod (possibly in a few days, sadly I've submitted the mod during non-business days).

**Comment by sharlin073** [comment] 2021-04-03 11:56
Thanks for the details! And...oh. The new one not working really sucks... I hope you got some services for free or refund :(

I'll be looking forward to it. Seems like I'll receive a notification in some days. I turned off No-pillaring for those reasons and it seems like it is really balanced now.
